"""identity: users, consents, credentials, codes, sessions, resets, devices

Revision ID: 0003_identity
Revises: 0002_platform_idempotency
Create Date: 2026-09-24 23:22:04.812373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_identity'
down_revision = '0002_platform_idempotency'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dashboard', sa.String(length=30), nullable=False),
    sa.Column('signed_up_with', sa.String(length=10), nullable=False),
    sa.Column('business_name', sa.String(length=80), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("dashboard IN ('informal_business', 'supplier')", name='ck_users_dashboard'),
    sa.CheckConstraint("signed_up_with IN ('email', 'google')", name='ck_users_signed_up_with'),
    sa.CheckConstraint("status IN ('unverified', 'active', 'deactivated')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    with op.batch_alter_table('users', schema='identity') as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_users_email'), ['email'], unique=True)

    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.CheckConstraint("document IN ('privacy_policy', 'terms_of_use')", name='ck_consents_document'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    with op.batch_alter_table('consents', schema='identity') as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_consents_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    with op.batch_alter_table('devices', schema='identity') as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_devices_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_devices_one_active_per_user', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))

    op.create_table('email_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('verify_email')", name='ck_email_codes_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    with op.batch_alter_table('email_codes', schema='identity') as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_email_codes_user_id'), ['user_id'], unique=False)

    op.create_table('password_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='identity'
    )
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='identity'
    )
    with op.batch_alter_table('password_resets', schema='identity') as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('refresh_jti', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['identity.devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_jti'),
    schema='identity'
    )
    with op.batch_alter_table('sessions', schema='identity') as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema='identity') as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_sessions_user_id'))

    op.drop_table('sessions', schema='identity')
    with op.batch_alter_table('password_resets', schema='identity') as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_password_resets_user_id'))

    op.drop_table('password_resets', schema='identity')
    op.drop_table('password_credentials', schema='identity')
    with op.batch_alter_table('email_codes', schema='identity') as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_email_codes_user_id'))

    op.drop_table('email_codes', schema='identity')
    with op.batch_alter_table('devices', schema='identity') as batch_op:
        batch_op.drop_index('uq_devices_one_active_per_user', postgresql_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_identity_devices_user_id'))

    op.drop_table('devices', schema='identity')
    with op.batch_alter_table('consents', schema='identity') as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_consents_user_id'))

    op.drop_table('consents', schema='identity')
    with op.batch_alter_table('users', schema='identity') as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_users_email'))

    op.drop_table('users', schema='identity')
    # ### end Alembic commands ###
