"""audit: append-only audit_events

Revision ID: 0004_audit
Revises: 0003_identity
Create Date: 2026-09-25 00:14:30.303903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0004_audit'
down_revision = '0003_identity'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('operating_system', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    with op.batch_alter_table('audit_events', schema='audit') as batch_op:
        batch_op.create_index('ix_audit_events_email', ['email'], unique=False)
        batch_op.create_index('ix_audit_events_event_time', ['event_name', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_events_user_time', ['user_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###

    # APPEND-ONLY: history can't be edited or deleted, not even by the app.
    op.execute("""
        CREATE OR REPLACE FUNCTION audit.forbid_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit.audit_events is append-only (% blocked)', TG_OP;
        END;
        $$;
    """)
    op.execute("""
        CREATE TRIGGER audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit.audit_events
        FOR EACH ROW EXECUTE FUNCTION audit.forbid_change();
    """)
    op.execute("""
        CREATE TRIGGER audit_events_no_truncate
        BEFORE TRUNCATE ON audit.audit_events
        FOR EACH STATEMENT EXECUTE FUNCTION audit.forbid_change();
    """)


def downgrade():
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit.audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit.audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit.forbid_change()")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema='audit') as batch_op:
        batch_op.drop_index('ix_audit_events_user_time')
        batch_op.drop_index('ix_audit_events_event_time')
        batch_op.drop_index('ix_audit_events_email')

    op.drop_table('audit_events', schema='audit')
    # ### end Alembic commands ###
