"""identity: google_identities

Revision ID: 0005_google_identities
Revises: 0004_audit
Create Date: 2026-09-25 00:36:50.193211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005_google_identities'
down_revision = '0004_audit'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=False),
    sa.Column('email_at_link', sa.String(length=254), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('google_sub'),
    schema='identity'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_identities', schema='identity')
    # ### end Alembic commands ###
