"""trader: business_profiles

Revision ID: 0007_business_profiles
Revises: 0006_two_factor
Create Date: 2026-09-25 06:33:16.418064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0007_business_profiles'
down_revision = '0006_two_factor'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.String(length=20), nullable=True),
    sa.Column('trade', sa.String(length=30), nullable=True),
    sa.Column('owner_name', sa.String(length=80), nullable=True),
    sa.Column('years_trading', sa.String(length=10), nullable=True),
    sa.Column('cellphone', sa.String(length=10), nullable=True),
    sa.Column('sole_trader', sa.Boolean(), nullable=False),
    sa.Column('cipc_number', sa.String(length=14), nullable=True),
    sa.Column('cipc_status', sa.String(length=20), nullable=True),
    sa.Column('cipc_registered_name', sa.String(length=160), nullable=True),
    sa.Column('cipc_entity_type', sa.String(length=60), nullable=True),
    sa.Column('cipc_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('building', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=160), nullable=True),
    sa.Column('suburb', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('restock', sa.String(length=20), nullable=True),
    sa.Column('spend', sa.String(length=20), nullable=True),
    sa.Column('payment', sa.String(length=10), nullable=True),
    sa.Column('fulfilment', sa.String(length=10), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("business_type IS NULL OR business_type IN ('builder', 'spaza', 'other')", name='ck_business_profiles_business_type'),
    sa.CheckConstraint("cipc_status IS NULL OR cipc_status IN ('pending', 'verified', 'owner_unconfirmed', 'deregistered', 'not_found', 'unavailable')", name='ck_business_profiles_cipc_status'),
    sa.CheckConstraint("fulfilment IS NULL OR fulfilment IN ('delivery', 'collect', 'either')", name='ck_business_profiles_fulfilment'),
    sa.CheckConstraint("payment IS NULL OR payment IN ('payfast', 'cash', 'both')", name='ck_business_profiles_payment'),
    sa.CheckConstraint("restock IS NULL OR restock IN ('daily', 'weekly', 'fortnightly', 'monthly')", name='ck_business_profiles_restock'),
    sa.CheckConstraint("spend IS NULL OR spend IN ('under_1k', '1k_5k', '5k_20k', 'over_20k')", name='ck_business_profiles_spend'),
    sa.CheckConstraint("trade IS NULL OR trade IN ('general_builder', 'plumber', 'electrician', 'carpenter', 'painter_tiler', 'other_trade')", name='ck_business_profiles_trade'),
    sa.CheckConstraint("years_trading IS NULL OR years_trading IN ('under_1', '1_3', '3_plus')", name='ck_business_profiles_years_trading'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='trader'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profiles', schema='trader')
    # ### end Alembic commands ###
