"""media and profile images

Revision ID: 0008_media
Revises: 0007_business_profiles
Create Date: 2026-09-25 07:01:45.259036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008_media'
down_revision = '0007_business_profiles'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_upload_intents',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id'),
    schema='platform'
    )
    with op.batch_alter_table('media_upload_intents', schema='platform') as batch_op:
        batch_op.create_index('ix_media_upload_intents_status_expires_at', ['status', 'expires_at'], unique=False)

    op.create_table('media_upload_records',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    with op.batch_alter_table('media_upload_records', schema='platform') as batch_op:
        batch_op.create_index('ix_media_upload_records_account_id_created_at', ['account_id', 'created_at'], unique=False)

    op.create_table('business_profile_images',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=500), nullable=False),
    sa.Column('secure_url', sa.String(length=1000), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('scan_provider', sa.String(length=50), nullable=True),
    sa.Column('scan_result', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id'),
    schema='trader'
    )
    with op.batch_alter_table('business_profile_images', schema='trader') as batch_op:
        batch_op.create_index('ix_business_profile_images_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('business_profiles', schema='trader') as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profiles', schema='trader') as batch_op:
        batch_op.drop_column('profile_image_url')

    with op.batch_alter_table('business_profile_images', schema='trader') as batch_op:
        batch_op.drop_index('ix_business_profile_images_user_id')

    op.drop_table('business_profile_images', schema='trader')
    with op.batch_alter_table('media_upload_records', schema='platform') as batch_op:
        batch_op.drop_index('ix_media_upload_records_account_id_created_at')

    op.drop_table('media_upload_records', schema='platform')
    with op.batch_alter_table('media_upload_intents', schema='platform') as batch_op:
        batch_op.drop_index('ix_media_upload_intents_status_expires_at')

    op.drop_table('media_upload_intents', schema='platform')
    # ### end Alembic commands ###
