"""trader: credit book (customers, entries, payments, corrections)

Revision ID: 0011_credit_book
Revises: 0010_business_name_to_profile
Create Date: 2026-09-25 12:20:11.409869

Customers only (docs/teammate/feedback/DECISION_credit_book.txt). Entries,
payments and corrections are never deleted; a customer is anonymised.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011_credit_book'
down_revision = '0010_business_name_to_profile'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_customers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("phone IS NULL OR phone ~ '^0[6-8][0-9]{8}$'", name='ck_credit_customers_phone'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('credit_customers', schema='trader') as batch_op:
        batch_op.create_index('ix_credit_customers_user_id', ['user_id'], unique=False)

    op.create_table('credit_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('given_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'paid', 'cancelled')", name='ck_credit_entries_status'),
    sa.CheckConstraint('amount_cents > 0 AND amount_cents <= 10000000', name='ck_credit_entries_amount'),
    sa.CheckConstraint('due_on >= given_on', name='ck_credit_entries_due_after_given'),
    sa.ForeignKeyConstraint(['customer_id'], ['trader.credit_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('credit_entries', schema='trader') as batch_op:
        batch_op.create_index('ix_credit_entries_user_status_due', ['user_id', 'status', 'due_on'], unique=False)

    op.create_table('credit_corrections',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('before_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('after_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('before_due_on', sa.Date(), nullable=False),
    sa.Column('after_due_on', sa.Date(), nullable=False),
    sa.Column('before_description', sa.String(length=120), nullable=False),
    sa.Column('after_description', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('correction', 'cancellation')", name='ck_credit_corrections_kind'),
    sa.ForeignKeyConstraint(['entry_id'], ['trader.credit_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('credit_corrections', schema='trader') as batch_op:
        batch_op.create_index('ix_credit_corrections_entry_id', ['entry_id'], unique=False)

    op.create_table('credit_payments',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_credit_payments_amount'),
    sa.ForeignKeyConstraint(['entry_id'], ['trader.credit_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('credit_payments', schema='trader') as batch_op:
        batch_op.create_index('ix_credit_payments_entry_id', ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_payments', schema='trader') as batch_op:
        batch_op.drop_index('ix_credit_payments_entry_id')

    op.drop_table('credit_payments', schema='trader')
    with op.batch_alter_table('credit_corrections', schema='trader') as batch_op:
        batch_op.drop_index('ix_credit_corrections_entry_id')

    op.drop_table('credit_corrections', schema='trader')
    with op.batch_alter_table('credit_entries', schema='trader') as batch_op:
        batch_op.drop_index('ix_credit_entries_user_status_due')

    op.drop_table('credit_entries', schema='trader')
    with op.batch_alter_table('credit_customers', schema='trader') as batch_op:
        batch_op.drop_index('ix_credit_customers_user_id')

    op.drop_table('credit_customers', schema='trader')
    # ### end Alembic commands ###
