"""supplier: suppliers, products, import_jobs

Suppliers and their catalogues, filled by a supplier's own system or the
seed files through one feed (integration/services/feed_loader.py).
import_jobs records every feed run, row errors included.

Revision ID: 0012_supplier_catalogue
Revises: 0011_drop_airtime_category
Create Date: 2026-09-25 16:46:29.456521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0012_supplier_catalogue'
down_revision = '0011_drop_airtime_category'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('trading_name', sa.String(length=120), nullable=False),
    sa.Column('legal_name', sa.String(length=160), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('vat_number', sa.String(length=10), nullable=True),
    sa.Column('orders_email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('brand_color', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('street', sa.String(length=160), nullable=False),
    sa.Column('suburb', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('province', sa.String(length=60), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivers', sa.Boolean(), nullable=False),
    sa.Column('delivery_radius_km', sa.Integer(), nullable=False),
    sa.Column('delivery_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('free_delivery_over_cents', sa.BigInteger(), nullable=True),
    sa.Column('collect', sa.Boolean(), nullable=False),
    sa.Column('accepts_in_app', sa.Boolean(), nullable=False),
    sa.Column('accepts_cash', sa.Boolean(), nullable=False),
    sa.Column('cash_limit_cents', sa.BigInteger(), nullable=True),
    sa.Column('minimum_order_cents', sa.BigInteger(), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('payout_merchant_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("categories <@ ARRAY['food_grocery', 'beverages', 'snacks_confectionery', 'bakery', 'dairy_chilled', 'fresh_produce', 'meat_frozen', 'household_cleaning', 'personal_care', 'baby_family', 'packaging_disposable', 'stationery_school', 'clothing_apparel', 'fragrances_beauty', 'phone_accessories', 'building_materials', 'plumbing', 'electrical', 'tools_hardware', 'paint_finishes', 'other']::varchar[]", name='ck_suppliers_categories'),
    sa.CheckConstraint("status IN ('active', 'paused')", name='ck_suppliers_status'),
    sa.CheckConstraint('accepts_cash OR cash_limit_cents IS NULL', name='ck_suppliers_cash_limit_needs_cash'),
    sa.CheckConstraint('accepts_in_app OR accepts_cash', name='ck_suppliers_takes_some_payment'),
    sa.CheckConstraint('cash_limit_cents IS NULL OR cash_limit_cents > 0', name='ck_suppliers_cash_limit'),
    sa.CheckConstraint('delivers OR collect', name='ck_suppliers_delivers_or_collect'),
    sa.CheckConstraint('delivery_fee_cents >= 0 AND minimum_order_cents >= 0', name='ck_suppliers_money'),
    sa.CheckConstraint('delivery_radius_km >= 0 AND delivery_radius_km <= 200', name='ck_suppliers_delivery_radius'),
    sa.CheckConstraint('free_delivery_over_cents IS NULL OR free_delivery_over_cents > 0', name='ck_suppliers_free_over'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    schema='supplier'
    )
    op.create_table('import_jobs',
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('deactivated', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refused_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('seed', 'integration_api')", name='ck_import_jobs_source'),
    sa.CheckConstraint("status IN ('finished', 'refused')", name='ck_import_jobs_status'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='supplier'
    )
    with op.batch_alter_table('import_jobs', schema='supplier') as batch_op:
        batch_op.create_index('ix_import_jobs_supplier_created', ['supplier_id', 'created_at'], unique=False)

    op.create_table('products',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=64), nullable=False),
    sa.Column('unit_barcode', sa.String(length=13), nullable=True),
    sa.Column('case_barcode', sa.String(length=14), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('pack_size', sa.String(length=60), nullable=False),
    sa.Column('units_per_pack', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price_cents', sa.BigInteger(), nullable=False),
    sa.Column('compare_at_price_cents', sa.BigInteger(), nullable=True),
    sa.Column('vat_rate', sa.String(length=10), nullable=False),
    sa.Column('vat_included', sa.Boolean(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('max_qty', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('food_grocery', 'beverages', 'snacks_confectionery', 'bakery', 'dairy_chilled', 'fresh_produce', 'meat_frozen', 'household_cleaning', 'personal_care', 'baby_family', 'packaging_disposable', 'stationery_school', 'clothing_apparel', 'fragrances_beauty', 'phone_accessories', 'building_materials', 'plumbing', 'electrical', 'tools_hardware', 'paint_finishes', 'other')", name='ck_products_category'),
    sa.CheckConstraint("unit IN ('each', 'pack', 'case', 'bag', 'box', 'bottle', 'tin', 'tray', 'crate', 'bundle', 'roll', 'sheet', 'length', 'cube', 'pallet', 'kg', 'litre', 'metre')", name='ck_products_unit'),
    sa.CheckConstraint("vat_rate IN ('standard', 'zero')", name='ck_products_vat_rate'),
    sa.CheckConstraint('compare_at_price_cents IS NULL OR compare_at_price_cents > price_cents', name='ck_products_compare_at'),
    sa.CheckConstraint('min_qty >= 1 AND max_qty >= min_qty AND max_qty <= 1000', name='ck_products_qty'),
    sa.CheckConstraint('price_cents > 0', name='ck_products_price'),
    sa.CheckConstraint('stock_qty >= 0', name='ck_products_stock'),
    sa.CheckConstraint('units_per_pack >= 1', name='ck_products_units_per_pack'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name='ck_products_weight'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_code', name='uq_products_supplier_product_code'),
    schema='supplier'
    )
    with op.batch_alter_table('products', schema='supplier') as batch_op:
        batch_op.create_index('ix_products_supplier_category', ['supplier_id', 'category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema='supplier') as batch_op:
        batch_op.drop_index('ix_products_supplier_category')

    op.drop_table('products', schema='supplier')
    with op.batch_alter_table('import_jobs', schema='supplier') as batch_op:
        batch_op.drop_index('ix_import_jobs_supplier_created')

    op.drop_table('import_jobs', schema='supplier')
    op.drop_table('suppliers', schema='supplier')
    # ### end Alembic commands ###
