"""trader: jobs, job stages, job sign-offs

Revision ID: 0012_jobs
Revises: 0011_credit_book
Create Date: 2026-09-25 15:27:57.381031

Jobs paid in stages; each stage gets a camera photo (server time + SHA-256)
and a client sign-off by one-use link. job_sign_offs keeps every attempt,
both amounts; tickets are stored only as HMACs.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012_jobs'
down_revision = '0011_credit_book'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('client_name', sa.String(length=60), nullable=False),
    sa.Column('client_phone', sa.String(length=10), nullable=False),
    sa.Column('place', sa.String(length=120), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("client_phone ~ '^0[6-8][0-9]{8}$'", name='ck_jobs_client_phone'),
    sa.CheckConstraint("status IN ('active', 'done')", name='ck_jobs_status'),
    sa.CheckConstraint('total_cents > 0 AND total_cents <= 500000000', name='ck_jobs_total'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('jobs', schema='trader') as batch_op:
        batch_op.create_index('ix_jobs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('job_stages',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo_public_id', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('photo_sha256', sa.String(length=64), nullable=True),
    sa.Column('photo_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('builder_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('client_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('client_note', sa.String(length=200), nullable=True),
    sa.Column('sign_off_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('not_started', 'photo_taken', 'waiting', 'confirmed', 'amounts_dont_match')", name='ck_job_stages_status'),
    sa.CheckConstraint('amount_cents > 0', name='ck_job_stages_amount'),
    sa.ForeignKeyConstraint(['job_id'], ['trader.jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'position', name='uq_job_stages_position'),
    schema='trader'
    )
    op.create_table('job_sign_offs',
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticket_hash', sa.String(length=64), nullable=False),
    sa.Column('builder_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('client_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('client_note', sa.String(length=200), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('via', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('confirmed', 'amounts_dont_match', 'not_yet')", name='ck_job_sign_offs_outcome'),
    sa.CheckConstraint('builder_amount_cents >= 0', name='ck_job_sign_offs_builder_amount'),
    sa.CheckConstraint('client_amount_cents IS NULL OR client_amount_cents >= 0', name='ck_job_sign_offs_client_amount'),
    sa.ForeignKeyConstraint(['stage_id'], ['trader.job_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_hash'),
    schema='trader'
    )
    with op.batch_alter_table('job_sign_offs', schema='trader') as batch_op:
        batch_op.create_index('ix_job_sign_offs_stage_id', ['stage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_sign_offs', schema='trader') as batch_op:
        batch_op.drop_index('ix_job_sign_offs_stage_id')

    op.drop_table('job_sign_offs', schema='trader')
    op.drop_table('job_stages', schema='trader')
    with op.batch_alter_table('jobs', schema='trader') as batch_op:
        batch_op.drop_index('ix_jobs_user_status')

    op.drop_table('jobs', schema='trader')
    # ### end Alembic commands ###
