"""trader: supplier_connections

Which suppliers a trader is connected to; only those can be ordered from.
Disconnecting soft-deletes (history kept); one live row per pair.

Revision ID: 0015_supplier_connections
Revises: 0014_supplier_catalogue
Create Date: 2026-09-25 20:22:37.827086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0015_supplier_connections'
down_revision = '0014_supplier_catalogue'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('supplier_connections', schema='trader') as batch_op:
        batch_op.create_index(batch_op.f('ix_trader_supplier_connections_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_supplier_connections_live', ['user_id', 'supplier_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_connections', schema='trader') as batch_op:
        batch_op.drop_index('uq_supplier_connections_live', postgresql_where=sa.text('is_deleted = false'))
        batch_op.drop_index(batch_op.f('ix_trader_supplier_connections_user_id'))

    op.drop_table('supplier_connections', schema='trader')
    # ### end Alembic commands ###
