"""supplier: product image links

Up to 7 photo links per product (our Cloudinary only), sent in the feed
like any other column. Existing products get none.

Revision ID: 0016_product_image_links
Revises: 0015_supplier_connections
Create Date: 2026-09-25 21:20:29.149792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0016_product_image_links'
down_revision = '0015_supplier_connections'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema='supplier') as batch_op:
        batch_op.add_column(sa.Column('image_urls', postgresql.ARRAY(sa.String(length=500)), nullable=False, server_default='{}'))
        batch_op.create_check_constraint('ck_products_images', 'cardinality(image_urls) <= 7')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema='supplier') as batch_op:
        batch_op.drop_constraint('ck_products_images', type_='check')
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
