"""commerce: orders

Orders, their lines (a snapshot of each product at order time) and an
append-only event history; and the sequence behind order references
(AKZ-<year>-<number>), starting at 101.

Revision ID: 0017_orders
Revises: 0016_product_image_links
Create Date: 2026-09-25 23:32:33.750205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0017_orders'
down_revision = '0016_product_image_links'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE SEQUENCE commerce.order_number_seq START WITH 101')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('fulfilment', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('subtotal_cents', sa.BigInteger(), nullable=False),
    sa.Column('delivery_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pay_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("fulfilment IN ('delivery', 'collect')", name='ck_orders_fulfilment'),
    sa.CheckConstraint("payment_method IN ('in_app', 'cash')", name='ck_orders_payment_method'),
    sa.CheckConstraint("payment_status IN ('unpaid', 'paid', 'cash_due', 'confirmed_by_both', 'refunded')", name='ck_orders_payment_status'),
    sa.CheckConstraint("status IN ('awaiting_payment', 'placed', 'accepted', 'out_for_delivery', 'ready_for_collection', 'delivered', 'collected', 'rejected', 'cancelled', 'expired')", name='ck_orders_status'),
    sa.CheckConstraint('subtotal_cents > 0 AND delivery_fee_cents >= 0 AND total_cents = subtotal_cents + delivery_fee_cents', name='ck_orders_money'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference'),
    schema='commerce'
    )
    with op.batch_alter_table('orders', schema='commerce') as batch_op:
        batch_op.create_index('ix_orders_supplier_status', ['supplier_id', 'status'], unique=False)
        batch_op.create_index('ix_orders_user_placed', ['user_id', 'placed_at'], unique=False)

    op.create_table('order_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('actor', sa.String(length=10), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("actor IN ('trader', 'supplier', 'system')", name='ck_order_events_actor'),
    sa.CheckConstraint("status IN ('awaiting_payment', 'placed', 'accepted', 'out_for_delivery', 'ready_for_collection', 'delivered', 'collected', 'rejected', 'cancelled', 'expired')", name='ck_order_events_status'),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='commerce'
    )
    with op.batch_alter_table('order_events', schema='commerce') as batch_op:
        batch_op.create_index(batch_op.f('ix_commerce_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pack_size', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('vat_rate', sa.String(length=10), nullable=False),
    sa.Column('unit_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('qty > 0 AND unit_price_cents > 0 AND line_total_cents = qty * unit_price_cents', name='ck_order_lines_money'),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['supplier.products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='commerce'
    )
    with op.batch_alter_table('order_lines', schema='commerce') as batch_op:
        batch_op.create_index(batch_op.f('ix_commerce_order_lines_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema='commerce') as batch_op:
        batch_op.drop_index(batch_op.f('ix_commerce_order_lines_order_id'))

    op.drop_table('order_lines', schema='commerce')
    with op.batch_alter_table('order_events', schema='commerce') as batch_op:
        batch_op.drop_index(batch_op.f('ix_commerce_order_events_order_id'))

    op.drop_table('order_events', schema='commerce')
    with op.batch_alter_table('orders', schema='commerce') as batch_op:
        batch_op.drop_index('ix_orders_user_placed')
        batch_op.drop_index('ix_orders_supplier_status')

    op.drop_table('orders', schema='commerce')
    # ### end Alembic commands ###
    op.execute('DROP SEQUENCE commerce.order_number_seq')
