"""trader: builder network (profiles, saves, blocks, reports, job partners, partner payments, help posts)

Revision ID: 0018_builder_network
Revises: 0017_orders
Create Date: 2026-09-25 22:58:31.023840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0018_builder_network'
down_revision = '0017_orders'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder_blocks',
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_builder_blocks'),
    schema='trader'
    )
    with op.batch_alter_table('builder_blocks', schema='trader') as batch_op:
        batch_op.create_index(batch_op.f('ix_trader_builder_blocks_blocked_id'), ['blocked_id'], unique=False)

    op.create_table('builder_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trades', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('about', sa.String(length=80), nullable=False),
    sa.Column('travel_km', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('visible_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_job_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cardinality(trades) BETWEEN 1 AND 3', name='ck_builder_profiles_trades'),
    sa.CheckConstraint('travel_km IN (5, 10, 20, 40)', name='ck_builder_profiles_travel'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='trader'
    )
    op.create_table('builder_reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason IN ('fake', 'not_their_work', 'scam', 'rude', 'other')", name='ck_builder_reports_reason'),
    sa.ForeignKeyConstraint(['reported_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('builder_reports', schema='trader') as batch_op:
        batch_op.create_index(batch_op.f('ix_trader_builder_reports_reported_id'), ['reported_id'], unique=False)

    op.create_table('builder_saves',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('builder_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['builder_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'builder_id', name='uq_builder_saves'),
    schema='trader'
    )
    op.create_table('help_posts',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('trade', sa.String(length=20), nullable=False),
    sa.Column('stage_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('what', sa.String(length=200), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('suburb', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pay_kind', sa.String(length=10), nullable=False),
    sa.Column('pay_cents', sa.BigInteger(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('paid_when', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('picked_builder_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("paid_when IN ('stage_confirmed', 'daily', 'end')", name='ck_help_posts_paid_when'),
    sa.CheckConstraint("pay_cents > 0 AND ((pay_kind = 'fixed' AND pay_cents <= 20000000) OR (pay_kind = 'per_day' AND pay_cents <= 1000000 AND pay_cents * days <= 20000000))", name='ck_help_posts_pay'),
    sa.CheckConstraint("pay_kind IN ('fixed', 'per_day')", name='ck_help_posts_pay_kind'),
    sa.CheckConstraint("status IN ('open', 'filled', 'closed')", name='ck_help_posts_status'),
    sa.CheckConstraint('days BETWEEN 1 AND 60', name='ck_help_posts_days'),
    sa.ForeignKeyConstraint(['job_id'], ['trader.jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['picked_builder_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('help_posts', schema='trader') as batch_op:
        batch_op.create_index('ix_help_posts_open', ['status', 'trade', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trader_help_posts_owner_id'), ['owner_id'], unique=False)

    op.create_table('job_partners',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('builder_id', sa.UUID(), nullable=False),
    sa.Column('stage_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('trade', sa.String(length=20), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('pay_kind', sa.String(length=10), nullable=False),
    sa.Column('pay_cents', sa.BigInteger(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('paid_when', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("paid_when IN ('stage_confirmed', 'daily', 'end')", name='ck_job_partners_paid_when'),
    sa.CheckConstraint("pay_cents > 0 AND ((pay_kind = 'fixed' AND pay_cents <= 20000000) OR (pay_kind = 'per_day' AND pay_cents <= 1000000 AND pay_cents * days <= 20000000))", name='ck_job_partners_pay'),
    sa.CheckConstraint("pay_kind IN ('fixed', 'per_day')", name='ck_job_partners_pay_kind'),
    sa.CheckConstraint("status IN ('invited', 'accepted', 'declined')", name='ck_job_partners_status'),
    sa.CheckConstraint('days BETWEEN 1 AND 60', name='ck_job_partners_days'),
    sa.CheckConstraint('owner_id <> builder_id', name='ck_job_partners_not_self'),
    sa.ForeignKeyConstraint(['builder_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['trader.jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('job_partners', schema='trader') as batch_op:
        batch_op.create_index('ix_job_partners_builder', ['builder_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trader_job_partners_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trader_job_partners_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('uq_job_partners_live', ['job_id', 'builder_id'], unique=True, postgresql_where=sa.text("status <> 'declined'"))

    op.create_table('help_responses',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('builder_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['builder_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['trader.help_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'builder_id', name='uq_help_responses'),
    schema='trader'
    )
    with op.batch_alter_table('help_responses', schema='trader') as batch_op:
        batch_op.create_index(batch_op.f('ix_trader_help_responses_builder_id'), ['builder_id'], unique=False)

    op.create_table('partner_payments',
    sa.Column('job_partner_id', sa.UUID(), nullable=False),
    sa.Column('owner_cents', sa.BigInteger(), nullable=False),
    sa.Column('partner_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('waiting', 'confirmed', 'amounts_dont_match')", name='ck_partner_payments_status'),
    sa.CheckConstraint('owner_cents > 0 AND owner_cents <= 20000000', name='ck_partner_payments_owner'),
    sa.CheckConstraint('partner_cents IS NULL OR (partner_cents >= 0 AND partner_cents <= 20000000)', name='ck_partner_payments_partner'),
    sa.ForeignKeyConstraint(['job_partner_id'], ['trader.job_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('partner_payments', schema='trader') as batch_op:
        batch_op.create_index(batch_op.f('ix_trader_partner_payments_job_partner_id'), ['job_partner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_payments', schema='trader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_trader_partner_payments_job_partner_id'))

    op.drop_table('partner_payments', schema='trader')
    with op.batch_alter_table('help_responses', schema='trader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_trader_help_responses_builder_id'))

    op.drop_table('help_responses', schema='trader')
    with op.batch_alter_table('job_partners', schema='trader') as batch_op:
        batch_op.drop_index('uq_job_partners_live', postgresql_where=sa.text("status <> 'declined'"))
        batch_op.drop_index(batch_op.f('ix_trader_job_partners_owner_id'))
        batch_op.drop_index(batch_op.f('ix_trader_job_partners_job_id'))
        batch_op.drop_index('ix_job_partners_builder')

    op.drop_table('job_partners', schema='trader')
    with op.batch_alter_table('help_posts', schema='trader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_trader_help_posts_owner_id'))
        batch_op.drop_index('ix_help_posts_open')

    op.drop_table('help_posts', schema='trader')
    op.drop_table('builder_saves', schema='trader')
    with op.batch_alter_table('builder_reports', schema='trader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_trader_builder_reports_reported_id'))

    op.drop_table('builder_reports', schema='trader')
    op.drop_table('builder_profiles', schema='trader')
    with op.batch_alter_table('builder_blocks', schema='trader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_trader_builder_blocks_blocked_id'))

    op.drop_table('builder_blocks', schema='trader')
    # ### end Alembic commands ###
