"""commerce: payments

One row per attempt to pay an order through PayFast: the pay-link ticket
(hashed), the amount, and what PayFast's verified notification said.

Revision ID: 0018_payments
Revises: 0017_orders
Create Date: 2026-09-26 00:49:37.762444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0018_payments'
down_revision = '0017_orders'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('ticket_hash', sa.String(length=64), nullable=False),
    sa.Column('ticket_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_reference', sa.String(length=40), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('itn_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'complete', 'failed', 'cancelled')", name='ck_payments_status'),
    sa.CheckConstraint('amount_cents > 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_hash'),
    schema='commerce'
    )
    with op.batch_alter_table('payments', schema='commerce') as batch_op:
        batch_op.create_index(batch_op.f('ix_commerce_payments_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema='commerce') as batch_op:
        batch_op.drop_index(batch_op.f('ix_commerce_payments_order_id'))

    op.drop_table('payments', schema='commerce')
    # ### end Alembic commands ###
