"""trader: the order book (customer orders at a counter)

Five new tables: the menu (order_book_items) and each item's price
history (order_book_item_prices), one counter row per trader per day
(order_book_days), and orders with their lines as sold
(order_book_orders, order_book_lines). The server makes each order's
id; the phone's key is client_key, unique per trader
(CONTRACT_order_book.txt and its DECISION). Nothing existing changes.

Revision ID: 0021_order_book
Revises: 0020_food_seller
Create Date: 2026-09-26 07:56:30.495600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0021_order_book'
down_revision = '0020_food_seller'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_book_days',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('last_number >= 0', name='ck_order_book_days_last_number'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_order_book_days_user_day'),
    schema='trader'
    )
    op.create_table('order_book_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('ingredients', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("ingredients <@ ARRAY['quarter_loaf', 'bun', 'chips', 'polony', 'russian', 'vienna', 'cheese', 'egg', 'atchar', 'lettuce', 'beef_patty', 'chicken', 'wors', 'pap', 'stew', 'chakalaka', 'vetkoek', 'mince', 'cold_drink']::varchar[]", name='ck_order_book_items_ingredients'),
    sa.CheckConstraint('position >= 0', name='ck_order_book_items_position'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('order_book_items', schema='trader') as batch_op:
        batch_op.create_index('ix_order_book_items_user_active', ['user_id', 'active'], unique=False)

    op.create_table('order_book_orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_key', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('temp_number', sa.String(length=5), nullable=False),
    sa.Column('payment', sa.String(length=10), nullable=False),
    sa.Column('customer_name', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("payment IN ('cash', 'digital', 'later')", name='ck_order_book_orders_payment'),
    sa.CheckConstraint("status IN ('new', 'preparing', 'ready', 'collected', 'cancelled')", name='ck_order_book_orders_status'),
    sa.CheckConstraint('number > 0', name='ck_order_book_orders_number'),
    sa.CheckConstraint('total_cents >= 0', name='ck_order_book_orders_total'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_key', name='uq_order_book_orders_user_key'),
    sa.UniqueConstraint('user_id', 'day', 'number', name='uq_order_book_orders_user_day_number'),
    schema='trader'
    )
    with op.batch_alter_table('order_book_orders', schema='trader') as batch_op:
        batch_op.create_index('ix_order_book_orders_user_day', ['user_id', 'day'], unique=False)

    op.create_table('order_book_item_prices',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_cents > 0 AND price_cents <= 200000', name='ck_order_book_item_prices_price'),
    sa.ForeignKeyConstraint(['item_id'], ['trader.order_book_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('order_book_item_prices', schema='trader') as batch_op:
        batch_op.create_index('ix_order_book_item_prices_item_from', ['item_id', 'valid_from'], unique=False)

    op.create_table('order_book_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_cents > 0 AND price_cents <= 200000', name='ck_order_book_lines_price'),
    sa.CheckConstraint('qty > 0 AND qty <= 50', name='ck_order_book_lines_qty'),
    sa.ForeignKeyConstraint(['item_id'], ['trader.order_book_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['trader.order_book_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trader'
    )
    with op.batch_alter_table('order_book_lines', schema='trader') as batch_op:
        batch_op.create_index('ix_order_book_lines_item_id', ['item_id'], unique=False)
        batch_op.create_index('ix_order_book_lines_order_id', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_book_lines', schema='trader') as batch_op:
        batch_op.drop_index('ix_order_book_lines_order_id')
        batch_op.drop_index('ix_order_book_lines_item_id')

    op.drop_table('order_book_lines', schema='trader')
    with op.batch_alter_table('order_book_item_prices', schema='trader') as batch_op:
        batch_op.drop_index('ix_order_book_item_prices_item_from')

    op.drop_table('order_book_item_prices', schema='trader')
    with op.batch_alter_table('order_book_orders', schema='trader') as batch_op:
        batch_op.drop_index('ix_order_book_orders_user_day')

    op.drop_table('order_book_orders', schema='trader')
    with op.batch_alter_table('order_book_items', schema='trader') as batch_op:
        batch_op.drop_index('ix_order_book_items_user_active')

    op.drop_table('order_book_items', schema='trader')
    op.drop_table('order_book_days', schema='trader')
    # ### end Alembic commands ###
