"""platform: notifications (alerts with their read state) and their switches

Two new tables (CONTRACT_notifications.txt section 1): notifications --
one alert per (user_id, dedupe_key), kind = a template key, params filled
by the server, read_at -- and notification_settings (orders, jobs, credit;
security has no switch). Nothing existing changes.

Revision ID: 0023_notifications
Revises: 0022_trades
Create Date: 2026-09-26 13:09:04.253982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0023_notifications'
down_revision = '0022_trades'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('orders', sa.Boolean(), nullable=False),
    sa.Column('jobs', sa.Boolean(), nullable=False),
    sa.Column('credit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_notification_settings_user'),
    schema='platform'
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tab', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=True),
    sa.Column('link_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('account.locked', 'account.new_phone', 'account.password_changed', 'account.phones_signed_out', 'credit.due_today', 'help.interested', 'help.picked', 'job.amounts_dont_match', 'job.done', 'job.not_yet', 'job.stage_confirmed', 'order.accepted', 'order.awaiting_payment', 'order.collected', 'order.delivered', 'order.expired', 'order.on_its_way', 'order.on_its_way_cash', 'order.paid', 'order.ready', 'order.rejected', 'order.sent', 'partner.accepted', 'partner.declined', 'partner.invited', 'partner.payment_confirmed', 'partner.payment_mismatch', 'partner.payment_recorded')", name='ck_notifications_kind'),
    sa.CheckConstraint("link_type IS NULL OR link_type IN ('order', 'job', 'invite', 'help_post', 'credit', 'security')", name='ck_notifications_link_type'),
    sa.CheckConstraint("tab IN ('orders', 'inbox')", name='ck_notifications_tab'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notifications_user_dedupe'),
    schema='platform'
    )
    with op.batch_alter_table('notifications', schema='platform') as batch_op:
        batch_op.create_index('ix_notifications_user_tab_created', ['user_id', 'tab', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='platform') as batch_op:
        batch_op.drop_index('ix_notifications_user_tab_created')

    op.drop_table('notifications', schema='platform')
    op.drop_table('notification_settings', schema='platform')
    # ### end Alembic commands ###
